### ISSUE TITLE
Unhandled exception: Failed to find module 'nativescript-socketio'

### ISSUE THREAD

**Issue by vladpre92** [triniwiz/nativescript-ng2-socketio-demo#1]
Hi,

I'm getting the following error when I try to deploy this demo to Android:
`RuntimeException: Failed to find module: 'nativescript-socketio', relative to: /app/tns_module`
But I checked that folder and the module exists, so I don't know how to solve this problem.I have installed all dependencies.
I'm running on OSX.

Thanks!

**Comment by triniwiz** [comment]
@vladpre92 ios or android ?

**Comment by vladpre92** [comment]
Both. Thanks.

**Comment by triniwiz** [comment]
the plugin is only supported on android atm https://github.com/triniwiz/nativescript-socketio/issues/4

**Comment by mattpcaswell** [comment]
Happened for me on Windows for an android emulator.

**Comment by triniwiz** [comment]
You can upgrade nativescript-socketio to `1.1.5` for the fix it was missing the compiled .js file on npm https://github.com/triniwiz/nativescript-socketio/commit/ff81bd216be6b918c97ab411e7e344fe33b438d4

**Comment by jwhits** [comment]
I have just tried to run the demo app and I am getting the same issue for android.

```
app/login.ts(2,24): error TS2307: Cannot find module 'nativescript-socketio'.
app/main-page.ts(5,24): error TS2307: Cannot find module 'nativescript-socketio'.
```

**Comment by triniwiz** [comment]
This issue was fixed in https://github.com/triniwiz/nativescript-socketio/commit/6b1e186a9a44ac5b806bf1f182fe739df50137c4

**Comment by agrawal-mohit** [comment]
@triniwiz Would you be able to give us an idea, if and when can we expect a support for iOS ?
